{{- range $name, $values := .Values.services }}
{{- if $values.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ $name }}-service
  labels:
    app: {{ $.Release.Name }}-{{ $name }}-service
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    component: {{ $name }}-service
spec:
  type: {{ $values.service.type }}
  ports:
    - port: {{ $values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ $.Release.Name }}-{{ $name }}-service
    release: {{ $.Release.Name }}
{{- end }}
{{- end }} 