apiVersion: v1
kind: Namespace
metadata:
  name: e-commerce-saga
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: e-commerce-saga
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: e-commerce-saga
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
        resources:
          limits:
            memory: 256Mi
            cpu: 500m
          requests:
            memory: 128Mi
            cpu: 250m
      volumes:
      - name: mongo-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: e-commerce-saga
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: order-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: e-commerce-saga
spec:
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: quay.io/centos7/python-38-centos7:latest
        command: ["bash", "-c"]
        args:
          - |
            echo "Starting container setup..."
            pip install fastapi uvicorn pymongo
            
            echo "Creating application directory..."
            mkdir -p /app
            
            echo "Writing application code..."
            cat > /app/main.py << 'EOF'
            import logging
            from fastapi import FastAPI
            import pymongo
            
            # Configure logging
            logging.basicConfig(level=logging.INFO)
            logger = logging.getLogger("order-service")
            
            app = FastAPI(title="Order Service")
            
            @app.get("/")
            def read_root():
                logger.info("Root endpoint called")
                return {"message": "Order Service is running"}
            
            @app.get("/health")
            def health_check():
                logger.info("Health check endpoint called")
                return {"status": "healthy"}
                
            @app.get("/mongo-status")
            def mongo_status():
                logger.info("Mongo status endpoint called")
                try:
                    client = pymongo.MongoClient("mongodb://mongodb:27017/", serverSelectionTimeoutMS=5000)
                    info = client.server_info()
                    logger.info(f"Successfully connected to MongoDB: {info}")
                    return {"status": "connected", "version": info.get("version")}
                except Exception as e:
                    logger.error(f"Failed to connect to MongoDB: {str(e)}")
                    return {"status": "error", "message": str(e)}
            EOF
            
            echo "Starting application server..."
            cd /app && python -m uvicorn main:app --host 0.0.0.0 --port 8000 --log-level debug
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: 256Mi
            cpu: 300m
          requests:
            memory: 128Mi
            cpu: 150m
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: order-service
  namespace: e-commerce-saga
spec:
  to:
    kind: Service
    name: order-service
  port:
    targetPort: 8000 