nodeExporter:
  enabled: false

server:
  persistentVolume:
    enabled: true
    size: 8Gi

alertmanager:
  persistentVolume:
    enabled: true
    size: 2Gi

pushgateway:
  persistentVolume:
    enabled: true
    size: 2Gi 